
import { Message, GroundingSource } from "../types";
import JSZip from "jszip";

export const downloadBlob = (blob: Blob, fileName: string) => {
  const url = window.URL.createObjectURL(blob);
  const a = document.createElement('a');
  a.href = url;
  a.download = fileName;
  document.body.appendChild(a);
  a.click();
  window.URL.revokeObjectURL(url);
  document.body.removeChild(a);
};

export const exportToPDF = async (message: Message) => {
  // We generate a high-fidelity HTML document that acts as an "Intelligence Dossier"
  // This is superior to a plain TXT file and can be "Printed to PDF" by the user.
  const htmlContent = `
<!DOCTYPE html>
<html>
<head>
  <style>
    body { font-family: 'Segoe UI', Tahoma, Geneva, Verdana, sans-serif; background: #020617; color: #e2e8f0; padding: 40px; }
    .dossier { border: 1px solid #1e293b; padding: 40px; border-radius: 20px; max-width: 800px; margin: auto; background: #0f172a; box-shadow: 0 20px 50px rgba(0,0,0,0.5); }
    .header { border-bottom: 2px solid #06b6d4; padding-bottom: 20px; margin-bottom: 30px; display: flex; justify-content: space-between; align-items: flex-end; }
    .title { font-size: 24px; font-weight: 900; letter-spacing: -1px; text-transform: uppercase; color: #fff; }
    .meta { font-family: monospace; font-size: 10px; color: #64748b; text-transform: uppercase; letter-spacing: 2px; }
    .content { font-size: 16px; line-height: 1.6; color: #cbd5e1; white-space: pre-wrap; margin-bottom: 40px; }
    .media { margin-top: 20px; border-radius: 12px; overflow: hidden; border: 1px solid #334155; }
    .media img { width: 100%; height: auto; }
    .grounding { margin-top: 30px; padding: 20px; background: #1e293b; border-radius: 12px; }
    .grounding-title { font-size: 12px; font-weight: bold; color: #06b6d4; margin-bottom: 10px; text-transform: uppercase; }
    .footer { margin-top: 50px; text-align: center; border-top: 1px solid #1e293b; padding-top: 20px; font-size: 10px; color: #475569; letter-spacing: 4px; }
  </style>
</head>
<body>
  <div class="dossier">
    <div class="header">
      <div>
        <div class="title">Neosphere AI Intelligence Dossier</div>
        <div class="meta">Classification: TOP SECRET // NEURAL OUTPUT</div>
      </div>
      <div class="meta" style="text-align: right;">
        REF_ID: ${message.id}<br>
        SYNC_TIME: ${new Date(message.timestamp).toISOString()}
      </div>
    </div>
    
    <div class="content">${message.content}</div>

    ${message.mediaUrl ? `
      <div class="media">
        ${message.mediaType === 'image' ? `<img src="${message.mediaUrl}" />` : `<div style="padding: 40px; text-align: center;">[VIDEO ASSET: ${message.id}]</div>`}
      </div>
    ` : ''}

    ${message.groundingSources && message.groundingSources.length > 0 ? `
      <div class="grounding">
        <div class="grounding-title">Verified Neural Grounding</div>
        ${message.groundingSources.map(s => `<div style="font-size: 11px; margin-bottom: 4px;">• <a href="${s.uri}" style="color: #38bdf8; text-decoration: none;">${s.title || 'Data Source'}</a></div>`).join('')}
      </div>
    ` : ''}

    <div class="footer">
      GENERATED BY NEOSPHERE AUTONOMOUS ECOSYSTEM // END OF REPORT
    </div>
  </div>
</body>
</html>
  `;
  const blob = new Blob([htmlContent], { type: 'text/html' });
  downloadBlob(blob, `NEOSPHERE_DOSSIER_${message.id}.html`);
};

export const exportToPPT = async (message: Message) => {
  // Simulated high-fidelity PPT summary
  const content = `
NEOSPHERE PRESENTATION MODULE
REPORT ID: ${message.id}
----------------------------------------
SLIDE 1: MISSION OVERVIEW
Agent Identity: ${message.agentId?.toUpperCase() || 'CORE'}
System Status: Stable

SLIDE 2: SYNAPTIC INSIGHTS
Executive Summary:
${message.content.substring(0, 500)}

SLIDE 3: MEDIA ATTACHMENTS
Asset Type: ${message.mediaType?.toUpperCase() || 'NONE'}
${message.mediaUrl ? 'Asset Attached in Package' : 'No Visuals Generated'}

SLIDE 4: SOURCE GROUNDING
${message.groundingSources?.map(s => `• ${s.title}: ${s.uri}`).join('\n') || 'Internal System Knowledge'}

----------------------------------------
AUTHENTICATION HASH: ${btoa(message.id)}
`;
  const blob = new Blob([content], { type: 'application/vnd.ms-powerpoint' });
  downloadBlob(blob, `NEOSPHERE_PRESENTATION_${message.id}.ppt`);
};

export const exportAlbumAsZip = async (messages: Message[]) => {
  const zip = new JSZip();
  const root = zip.folder("NEOSPHERE_NEURAL_ARCHIVE");
  const media = root?.folder("MEDIA_ASSETS");
  const data = root?.folder("RAW_DATA");

  for (const msg of messages) {
    // Add raw text data
    data?.file(`MANIFEST_${msg.id}.txt`, `NEOSPHERE ARCHIVE BLOCK\nTIMESTAMP: ${new Date(msg.timestamp).toLocaleString()}\n\nCONTENT:\n${msg.content}`);

    // Add media assets (images/videos)
    if (msg.mediaUrl) {
      try {
        // Handle data URLs or standard URIs
        const response = await fetch(msg.mediaUrl);
        const blob = await response.blob();
        
        let extension = 'bin';
        if (msg.mediaType === 'image') extension = 'png';
        else if (msg.mediaType === 'video') extension = 'mp4';
        else if (msg.mediaType === 'audio') extension = 'wav';
        
        media?.file(`ASSET_${msg.id}.${extension}`, blob);
      } catch (e) {
        console.error("Neural fetch failed for ZIP inclusion:", e);
      }
    }
  }

  const zipBlob = await zip.generateAsync({ type: "blob" });
  downloadBlob(zipBlob, `NEOSPHERE_ARCHIVE_${Date.now()}.zip`);
};

export const shareToSocial = async (message: Message, platform?: 'x' | 'linkedin' | 'instagram') => {
  const cleanContent = message.content.replace(/[#*`]/g, '');
  const text = `Neosphere AI Insight: ${cleanContent.substring(0, 180)}...`;
  const url = window.location.href;

  if (platform === 'x') {
    window.open(`https://twitter.com/intent/tweet?text=${encodeURIComponent(text)}&url=${encodeURIComponent(url)}`, '_blank');
  } else if (platform === 'linkedin') {
    window.open(`https://www.linkedin.com/sharing/share-offsite/?url=${encodeURIComponent(url)}`, '_blank');
  } else if (navigator.share) {
    try {
      await navigator.share({ title: 'Neosphere Neural Link', text, url });
    } catch (err) {}
  } else {
    await navigator.clipboard.writeText(`${text}\n\nUplink: ${url}`);
  }
};
